### PR TITLE
depends: libheif: update to 1.16.1

### PR DESCRIPTION
**Pull request by lrusak**
This updates libheif which should help remove some patches and make #20  easier.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Thanks a lot! Started to go currently over all binary add-ons and currently on inputstream.ffmpegdirect, will then also look to here about the AVIF support.

**Comment by bpmarinho** [comment]
Hello,
Will be there a plugin release with this change for Nexus?
- https://kodi.wiki/view/Add-on:HEIF_image_decoder

I'm asking because I have this issue - https://forum.libreelec.tv/thread/26589-heif-image-decoder-crashes-when-first-heif-image-has-to-be-decoded/?postID=180083#post180083 - and I was thinking if this improvement would fix it.

**Comment by lrusak** [comment]
> Hello,
> 
> Will be there a plugin release with this change for Nexus?
> 
> - https://kodi.wiki/view/Add-on:HEIF_image_decoder
> 
> 
> 
> I'm asking because I have this issue - https://forum.libreelec.tv/thread/26589-heif-image-decoder-crashes-when-first-heif-image-has-to-be-decoded/?postID=180083#post180083 - and I was thinking if this improvement would fix it.
> 
> 

I don't have plans to backport this change.

**Comment by bpmarinho** [comment]
> > Hello,
> > Will be there a plugin release with this change for Nexus?
> > 
> > * https://kodi.wiki/view/Add-on:HEIF_image_decoder
> > 
> > I'm asking because I have this issue - https://forum.libreelec.tv/thread/26589-heif-image-decoder-crashes-when-first-heif-image-has-to-be-decoded/?postID=180083#post180083 - and I was thinking if this improvement would fix it.
> 
> I don't have plans to backport this change.

I have moved to `Omega` nightly. It has same issue as before but not sure I'm using this version.
It shows `HEIF image decoder spiff-20.1.0.6`.

**Comment by bpmarinho** [comment]
> > > Hello,
> > > Will be there a plugin release with this change for Nexus?
> > > 
> > > * https://kodi.wiki/view/Add-on:HEIF_image_decoder
> > > 
> > > I'm asking because I have this issue - https://forum.libreelec.tv/thread/26589-heif-image-decoder-crashes-when-first-heif-image-has-to-be-decoded/?postID=180083#post180083 - and I was thinking if this improvement would fix it.
> > 
> > 
> > I don't have plans to backport this change.
> 
> I have moved to `Omega` nightly. It has same issue as before but not sure I'm using this version. It shows `HEIF image decoder spiff-20.1.0.6`.

Found out that my issue was. I have Raspberry Pi 02 and since HEIC plugin from my understanding uses HEVC, I needed to downgrade to version 9.2.8 to get the plugin to work.
It's mention in the bottom of this page
- https://wiki.libreelec.tv/hardware/raspberry-pi

> If you need HEVC support on older Raspberry Pi 01/2/3 hardware use LibreELEC 9.2.x and do not update to LibreELEC 10.x or 11.x.
>
> If you have Raspberry Pi 4 or 400 hardware, use LibreELEC 10.x or newer to benefit from better HEVC and 4K HDR support.

**Pull request merged**
